# Generated by Django 5.2.8 on 2025-11-15 00:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=120)),
                ('hs_code_hint', models.CharField(blank=True, max_length=16)),
                ('duty_rate_pct', models.FloatField(default=0.0)),
                ('vat_rate_pct', models.FloatField(default=20.0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('CLIENT', 'CLIENT'), ('AGENCY', 'AGENCY'), ('ADMIN', 'ADMIN')], default='CLIENT', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=80)),
                ('kyc_status', models.CharField(default='PENDING', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.FloatField()),
                ('declared_value', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(default='CREATED', max_length=20)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.customscategory')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_total_cents', models.IntegerField()),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('fee_platform_cents', models.IntegerField(default=0)),
                ('stripe_pi', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='REQUIRES_ACTION', max_length=20)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coreapp.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_country', models.CharField(max_length=2)),
                ('origin_city', models.CharField(max_length=80)),
                ('dest_country', models.CharField(max_length=2)),
                ('dest_city', models.CharField(max_length=80)),
                ('departure_at', models.DateTimeField()),
                ('arrival_eta', models.DateTimeField(blank=True, null=True)),
                ('capacity_kg', models.FloatField()),
                ('price_per_kg', models.FloatField()),
                ('status', models.CharField(default='PUBLISHED', max_length=20)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.agency')),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.trip'),
        ),
    ]
