# Generated by Django 5.2.8 on 2025-11-27 04:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='declared_value',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='notes',
        ),
        migrations.AddField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='customer_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='shipment',
            name='customer_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='customer_phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='coreapp.trip'),
        ),
    ]
