# Generated by Django 5.2.8 on 2026-04-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0016_payment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='home_delivery_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
